:PROPERTIES:
:ID:       a3ba500f-c6c9-4173-8db9-8ad715f79405
:END:
#+TITLE: My emacs doom configuration
#+AUTHOR: Cody Goodman
#+EMAIL: cody@codygman.dev
#+LANGUAGE: en
#+STARTUP: inlineimages
#+PROPERTY: header-args :cache yes :results silent :padline no

* A Note On The Structure Of This Document
This document attempts to motivate changes first by describing a workflow in
prose and presenting examples inline or linking to headings such as [[id:a09cbdef-c018-45ff-af40-bdd78c0d7edd][Make Org
Agenda look nicer]] when appropriate.

Perhaps it's always appropriate  to have a workflow description and then link to
the relevant hierarchical [[id:bc892078-e21e-4f4e-885c-44c0ade78420][Configuration]] tree section, but for now I'm going
with the mixed approach since [[https://github.com/alhassy/emacs.d/blob/master/README.org#a-life-configuring-emacs][that style can be very nice]].
* Managing Life With Org Mode
** Keep org files updated and avoid sync conficts
Doom doesn't turn on auto-revert mode by default, meaning a change made on my
phone that gets synced to my computer won't appear until I manually revert the
buffer with =revert-buffer=.

I backup my org files every 30 minutes and conflicts are a bigger pain, so let's
do that automatically:

#+begin_src emacs-lisp :tangle yes
(global-auto-revert-mode t)
#+end_src
** Capturing
*** Ideas
:PROPERTIES:
:ID:       783fc72a-92d9-4ee1-9d58-9e77486cc544
:END:
Any idea or note that comes to me throughout the day can be captured with a
simple capture template:

#+begin_src emacs-lisp :noweb-ref simple-todo-capture-template :tangle no :noweb yes
("i" "Quick Inbox Todo" entry (file+headline "~/gtd/inbox.org" "Inbox")
             "* TODO %?
<<default-capture-properties>>
" :prepend t)
#+end_src

I find it's a good idea to prepend these tasks by default so your freshest ideas
are near the top of the file. Perhaps that's a bad habit or reinforces not
curating or refiling things enough though.
*** Load Personal Or Work Capture Templates And Agendas
#+begin_src emacs-lisp :tangle yes
;; TODO hardcode hack
(setenv "EMACSFOR" "PERSONAL")
(when (string-equal nil (getenv "TRAVIS_OS_NAME"))
    (pcase (getenv "EMACSFOR")
      ("WORK" (load (expand-file-name "work.el" "~")))
      ("PERSONAL"
       (ignore-errors (load (expand-file-name "bsab/personal.el" "~")))
       )
      (_ (error "Please set the EMACSFOR variable to WORK or PERSONAL"))))
#+end_src
*** Oh Crap I Need To Drop Everything And Do X

Example: Stop configuring org for hours on end and clock in to "Go get dinner" :)

#+begin_src emacs-lisp :noweb-ref simple-todo-clocking-capture-template :tangle no :noweb yes
;; TODO don't use for GTD?
("T" "Todo" entry (file+headline "~/bsab/misc.org" "Misc")
             "* TODO %?
<<default-capture-properties>>
" :prepend t :clock-in t :clock-resume t)
#+end_src
*** Drag and drop support of images in org mode
:PROPERTIES:
:ID:       2f6b5dea-987b-4153-8dbd-07954c5d4777
:END:
Uses org-download and requires [[file:init.el::(org +dragndrop) ; organize your plain life in plain text][enabling drag and drop support in doom]]
*** Notes in existing projects
Just now I needed to capture the note:

"I like doom over my vanilla config because of the reload infrastructure and
benchmarking/timing information that is prevalent"

I wanted to be able to just capture it, but instead had to navigate to
=projects.org=, go to =Active Projects=, go to =try out doom emacs for possible
time savings=, find =notes on doom use through the week=.

Instead I'd like an =Note In Active Project= capture template where I could just
=SPC X a= (or using ivy to select that capture template text), type my note, and
then refile into any realistic level within =Projects.org -> Active Projects=
*** Projects
Projects may be created by from [[id:783fc72a-92d9-4ee1-9d58-9e77486cc544][Ideas/Notes]] I quickly captured

#+begin_src emacs-lisp :noweb-ref project-capture-template :tangle no :noweb yes
("p" "Project" entry (file+headline "~/org/projects.org" "Projects")
 (file "capture-templates/project-capture-template.org") :prepend t)
#+end_src

#+begin_src org :tangle ~/bsab/capture-templates/project-capture-template.org :mkdirp yes :noweb yes
,* TODO %? [/]
  <<default-capture-properties>>
,** TODO <1m project notes                  :plan:
         :PROPERTIES:
         :Effort:       00:01
         :END:
,** TODO project good/bad recap
#+end_src
*** Errands
:PROPERTIES:
:ID:       b0892384-d742-4f66-a7eb-013ab39fb3e2
:END:
Let's use org for random errands too:

#+begin_src emacs-lisp :noweb-ref project-capture-template :tangle no :noweb yes
("e" "Errand" entry (file+headline "~/amicody/errands.org" "Errands")
         "* TODO %?" :prepend t)
#+end_src
*** Groceries
:PROPERTIES:
:ID:       4fd1e906-91c0-42f4-9d0b-367ee13d2814
:END:
I use org to manage my grocery list as well:

#+begin_src emacs-lisp :noweb-ref grocery-capture-template :tangle no :noweb yes
("g" "Grocery Item" entry (file+headline "~/amicody/grocery.org" "Groceries")
         "* TODO %?" :prepend t)
#+end_src
*** Dinner
:PROPERTIES:
:ID:       a80d9edf-dabd-4dde-b267-ae743a0e4d00
:END:
"What did we have last Wednesday for dinner?" - Me or my girlfriend probably

"What do we usually watch Sundays recently?" - Me

We can use a reverse datetree capture template to answer those questions. This
depends on [[https://github.com/akirak/org-reverse-datetree][org-reverse-datetree]] whose example uses their [[https://github.com/akirak/org-starter#installation][org-starter]] package, so
we'll just install both in packages.

FIXME: Can we install packages in config.org too?

Here is our capture template:

#+begin_src emacs-lisp :noweb-ref org-starter-dinner-capture-template-unused :tangle no :noweb yes
(org-starter-def-capture "d"
  "Dinner Eat/Watch History"
  entry
  (file+function "~/amicody/dinner.org" org-reverse-datetree-goto-date-in-file)
  "* %?"
  :clock-in t :clock-resume t :empty-lines 1)
#+end_src

#+begin_src emacs-lisp :noweb-ref dinner-history-capture-template :tangle no :noweb yes
("d" "Dinner Eat/Watch History" entry (file+function "~/amicody/dinner.org" org-reverse-datetree-goto-date-in-file)
         "* %?")
#+end_src
*** Additions To Default Capture
**** TODO Screenshots: Quickly record information
:PROPERTIES:
:ID:       b02315a9-91db-4a3a-a7d2-c9dadfec5f87
:END:
not working in doom and really missing them

see [[id:41a15340-e9ab-4722-88ea-5774020a5418][org-download]]

NOTE: Default doom attach directory is ~/org/attach which isn't synced with phone
***** TODO view screenshots across devices (PC/Android Orgzly)
**** TODO clock in/out smartly on state change
*** Linking To Relevant Information During Capture Or Notes
**** Linking to recent git commits
***** TODO store all recent magit commits with org-store-link
****** example
I notice that =cw= is slower in my org files in doom emacs than in my vanilla
config and note that down, I call =org-insert-link= and find the most recent
commit to the relevant doom emacs config project.
*** TODO Quick screenshot ability is absolutely necessary
TODO: Doom doesn't seem to make =org-download-screenshot= available to us by default.

#+begin_src emacs-lisp :tangle yes
(setq org-download-screenshot-method
              (case system-type (gnu/linux "import %s") (darwin "screencapture -i %s")))
#+end_src

For some reason doom makes these "attach://" protocol links by default which don't
seem to display in org mode. Let's change it back to "file://" so images show inline:

Now that we have images inline though, some are *way* too large, let's default
them to be 500 px wide:

#+begin_src emacs-lisp :tangle yes
(setq org-download-image-org-width 400)
#+end_src

I would set =org-download-image-dir= but it seems doom is already automatically
putting them in ~/.attach which is fine for me.
*** linking or archiving webpages on the internet with org-web-tools

This is actually done in [[file:packages.el::(package! org-web-tools)][packages.el]] for now, but for posterity it looks like:

#+begin_src emacs-lisp :tangle no
(package! org-web-tools)
#+end_src

** Agenda: What should you be doing now?
The org agenda is quite a nice way to surface your notes into an actionable list
of priorities and scheduled items. Though we need to do some work to [[id:a09cbdef-c018-45ff-af40-bdd78c0d7edd][Make Org
Agenda look nicer]], it's well worth the effort.
** Viewing Org Files (prefer using agenda if possible)
*** Additions To Default Org Mode View
**** TODO hide properties by default
** Archiving
For a long time, I didn't even archive things out of fear I couldn't search
them. That changes today, and I'll do it by archiving into an
=archives/datetree.org=.

That frees me up to archive daily!

#+begin_src emacs-lisp :tangle yes
(setq org-archive-location "~/bsab/archives/datetree.org::datetree/* Finished Tasks")
#+end_src

While we're at it, let's make sure =org-search-view= includes all of our
archives by using the magic =agenda-archives= symbol:

#+begin_src emacs-lisp :tangle yes
(setq org-agenda-text-search-extra-files (list 'agenda-archives))
#+end_src
** Clocking
I like to clock things sometimes to get an idea where my day went. Clocks in
doom seem to not be in the property drawer by default, so let's fix that:

#+begin_src emacs-lisp :tangle yes
(setq org-log-into-drawer t
      org-log-state-notes-into-drawer t)
#+end_src
** Resources
*** https://github.com/alhassy/emacs.d/blob/master/README.org
** Org-roam (experimental)
*** Org-mode version of [[https://roamresearch.com/][Roam: A note-taking tool for networked thought.]]
this only seems to work from [[file:packages.el::package! org-roam]] so disabling by not tangling for now
#+begin_src emacs-lisp :tangle no
(package! org-roam)
#+end_src

Want to put it in here by default, hopefully this works since above didn't:

#+begin_src emacs-lisp :tangle yes
(after! org-roam (setq org-roam-directory "~/ztd/org-roam"))
#+end_src
* Configuration
:PROPERTIES:
:ID:       bc892078-e21e-4f4e-885c-44c0ade78420
:END:
** Personal Information
:PROPERTIES:
:header-args: :noweb-ref personal-info
:END:
*** Set full name
#+BEGIN_SRC emacs-lisp :tangle yes
(setq user-full-name "Cody Goodman")
#+END_SRC
*** Set email address
#+BEGIN_SRC emacs-lisp :tangle yes
(setq user-mail-address "cody@codygman.dev")
#+END_SRC
** Spell checking
*** load my personal dictionary
#+begin_src emacs-lisp :tangle yes
(setq ispell-personal-dictionary "~/gtd/files/ispell/personal/ispell_english")
#+end_src
** Doom Core
Here I setup my config for the =doom-emacs= [[doom:core/][core]]
*** [[doom:core/core.el][Core]]
**** Use =jf= instead of default doom =jk=
#+BEGIN_SRC emacs-lisp :tangle yes
(setq-default evil-escape-key-sequence "jf")
#+END_SRC
**** disable line numbers
#+begin_src emacs-lisp :tangle yes
(setq display-line-numbers-type nil)
#+end_src
** Doom Visual
*** font
#+begin_src emacs-lisp :tangle yes
(setq doom-font (font-spec :family "Source Code Pro" :size 17))
#+end_src
** Org Mode
*** start after org macro
:PROPERTIES:
:ID:       0c10ce60-0d6a-4317-9469-cf7f45651a84
:END:
#+begin_src emacs-lisp :tangle yes
(after! org
#+end_src
*** Enable linking with org uuid
#+begin_src emacs-lisp :tangle yes
(require 'org-id)
(setq org-id-link-to-org-use-id t)
#+end_src
*** org capture templates
:PROPERTIES:
:ID:       95e44ec7-c44b-4444-8b92-754330024e3e
:END:
#+begin_src emacs-lisp :tangle yes :noweb yes
(setq org-capture-templates
      '(
<<simple-todo-capture-template>>
<<project-capture-template>>
<<simple-todo-clocking-capture-template>>
<<grocery-capture-template>>
<<dinner-history-capture-template>>
        ))
#+end_src
*** default org capture heading properties
#+name: default-capture-properties
#+begin_src text
:PROPERTIES:
:ID:       %(org-id-uuid)
:CREATED: %U
:END:
#+end_src
*** basics
**** Here is where my org files live
#+begin_src emacs-lisp
(setq org-directory "~/gtd")
(setq org-agenda-files '("~/gtd" "~/amicody"))
#+end_src
**** These are my todo states
#+name: set-org-todo-keywords
#+begin_src emacs-lisp
  (setq org-todo-keywords
        '((sequence "TODO(t)" "STRT(s)" "IN-PROGRESS(i)" "NEXT(n)" "WAIT(w@/!)" "|" "DONE(d!)" "KILL(k@)")))
#+end_src
*** org-attach
Org attach is required to make [[id:2f6b5dea-987b-4153-8dbd-07954c5d4777][Drag and drop support of images in org mode]] work
#+begin_src emacs-lisp
(after! org-attach
  ;; (setq org-attach-id-dir "~/gtd/.attach")
  (setq org-attach-id-dir "/home/demo/gtd/.attach")
  )
#+end_src
*** org agenda
**** Use Org Super Agenda
#+begin_src emacs-lisp :tangle no :eval no
(setq org-super-agenda-header-map (make-sparse-keymap)) ;; don't break evil on org-super-agenda headings, see https://github.com/alphapapa/org-super-agenda/issues/50
(org-super-agenda-mode t)
(after! org-agenda (setq org-agenda-custom-commands
                         '(("d" "Dashboard"
                            (
                             (agenda ""
                              (
                               (org-agenda-overriding-header "Dashboard")
                               (org-agenda-span 'day)
                               (org-agenda-start-day (org-today))
                               (org-agenda-current-span 'day)
                               (org-super-agenda-groups
                                '(
                                  (:and (:scheduled today :habit t) :order 2  :name "Habits Today")
                                  (:name "Schedule" :time-grid t :order 3)
                                  (:name "Scheduled Earlier"
                                         :scheduled past
                                         :order 10
                                         )
                                  (:name "Must Do Today"
                                         :and (:deadline today :priority "A")
                                         :deadline today
                                         :and (:deadline past :priority "A")
                                         :and (:scheduled t :priority "A")
                                         :and (:scheduled past :priority "A")
                                         :deadline past
                                         :order 1
                                         )

                                  ;; dialy10m review not matching :/
                                  (:name "Daily 10m Review"
                                         :and (:habit t :regexp  "review")
                                         :order 0
                                         )
                                  (:log t :order 20)

                                  ))))

                             ))))

  )
#+end_src
**** Make Org Agenda look nicer
:PROPERTIES:
:ID:       a09cbdef-c018-45ff-af40-bdd78c0d7edd
:END:
***** remove =Scheduled: = text in front of org agenda items
It just takes up valuable space and doesn't have a use
#+begin_src emacs-lisp
(setq org-agenda-scheduled-leaders '("" ""))
#+end_src
*** end after org macro
#+begin_src emacs-lisp
)
#+end_src

*** dired
**** make sorting easy (see https://gitlab.com/xuhdev/dired-quick-sort)
#+begin_src emacs-lisp :tangle no :eval no
;; this is breaking things
(after! dired (dired-quick-sort-setup)) ;; don't think this works
#+end_src
