name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - uses: cachix/cachix-action@v2
      with:
        name: codygman4
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        # Only needed for private caches
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Run Emacs tests
      run: |
          EMACSFOR="PERSONAL" emacs -Q --batch --load load-init-then-test.el
